// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pojfjvjwwtgzcpmnpjwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvamZqdmp3d3RnemNwbW5wandlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzI4NjAsImV4cCI6MjA3NDA0ODg2MH0.emW-T73zhqtRK8f0eMrzs4ZudXUm9HZBvSEaMIc4NLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});